### ISSUE TITLE
Doesn't do anything

### ISSUE THREAD

**Issue by fireboy1919** [mattgibson/resque-scheduler-web#2]
All resque gems in my gem file:
```gem 'capistrano-resque', require: false
gem 'resque'
gem 'resque-scheduler'
gem 'resque-scheduler-web'
gem 'resque-loner'```

My routes.rb:
```Rails.application.routes.draw do
  mount ResqueWeb::Engine => "/resque_web"
end
```

Accessing /resque_web, and I see no tabs.

**Comment by mattgibson** [comment]
Thanks for the report. I'll try to replicate later this evening.

**Comment by mattgibson** [comment]
I replicated this on a clean Rails 4 app with your gems as outlined above. However, this is not a bug with resque-scheduler-web, but with resque-web: https://github.com/resque/resque-web/issues/62

To fix it (until that bug is sorted out), add the following line to your `Gemfile`:

`gem 'twitter-bootstrap-rails', '~>2.2.8'`
