### ISSUE TITLE
The resque-web Schedule tab has old/different data for each unicorn worker

### ISSUE THREAD

**Issue by nroose** [mattgibson/resque-scheduler-web#3]
This stuff is great! But I have one problem, which is that the Schedule tab on the resque web console seems to change between a few different sets if data, seemingly different snapshots in time. And if I restart the unicorns, it stays the same. This does not happen for the Overview or other tabs. Any help would be greatly appreciated.

https://github.com/resque/resque-scheduler/issues/482

**Comment by mattgibson** [comment]
Hi. Sorry for the delay - busy summer. Thanks for the report! 

I'm not quite sure what steps to take in order to start reproducing this. Can you give me any more details of your setup and the exact sequence of steps that cause this to happen? I am not quite sure how this would happen, as it seems to check what Rails env the job is scheduled in and then just displays them all. I didn't write this code initially and have only refactored it a bit, so I'm slightly uncertain how Resque and Redis interact here. Might be something I'm missing.

**Comment by nroose** [comment]
Oh.  Sorry.  I looked into the code.  It seems that it was fixed by making sure that resque-scheduler was running in dynamic mode.  We had some other issues around that as well.  It's all working great now that we set the env variable instead of trying to set that programmatically on initialization.

**Comment by mattgibson** [comment]
Ah, OK. Shall I close this then, or is there an issue to be fixed in this gem, but only under certain circumstances?

**Comment by nroose** [comment]
OK with me to close it.  I don't really understand why the static and dynamic modes need to exist, though.

**Comment by mattgibson** [comment]
I think the dynamic mode is so that the schedule can be changed programmatically rather than using a YAML file in the static version. Not sure what the use cases are, but it sort of makes sense, I suppose. Either way, I'll close this. Thanks again for the report.
